database:
  host: localhost
  database: ferries-db
  port: 3306
  username: user
  password: password
parse:
  endpoint: http://localhost:1337/parse
  application_id: abcdefgh
marinetraffic:
  api_key: abcdefgh
